export const products = [
  {
    id: 1,
    name: "Super Glasses Classic",
    description:
      "A timeless classic design with a modern twist, perfect for any occasion.",
    image: "/products/1.png",
    price: 49.99,
    size: "Medium",
    color: "Black",
    material: "Acetate",
    frameShape: "Square",
    lensType: "UV Protection",
    weight: "25g",
    availability: "In Stock",
  },
  {
    id: 2,
    name: "Super Glasses Aviator",
    description:
      "Stylish aviator glasses that offer both style and comfort, ideal for sunny days.",
    image: "/products/2.png",
    price: 59.99,
    size: "Large",
    color: "Gold",
    material: "Metal",
    frameShape: "Aviator",
    lensType: "Polarized",
    weight: "30g",
    availability: "In Stock",
  },
  {
    id: 3,
    name: "Super Glasses Retro",
    description:
      "Retro-inspired frames that bring a unique flair to any outfit.",
    image: "/products/3.png",
    price: 54.99,
    size: "Small",
    color: "Tortoise Shell",
    material: "Acetate",
    frameShape: "Round",
    lensType: "Blue Light Blocking",
    weight: "22g",
    availability: "In Stock",
  },
  {
    id: 4,
    name: "Super Glasses Urban",
    description: "Sleek and urban design, perfect for the modern minimalist.",
    image: "/products/4.png",
    price: 64.99,
    size: "Medium",
    color: "Matte Black",
    material: "Stainless Steel",
    frameShape: "Rectangle",
    lensType: "Scratch Resistant",
    weight: "27g",
    availability: "In Stock",
  },
  {
    id: 5,
    name: "Super Glasses Vintage",
    description:
      "Vintage-inspired frames for a bold, unique look that stands out.",
    image: "/products/5.png",
    price: 69.99,
    size: "Medium",
    color: "Amber",
    material: "Acetate",
    frameShape: "Cat-Eye",
    lensType: "Gradient Tint",
    weight: "24g",
    availability: "Limited Stock",
  },
  {
    id: 6,
    name: "Super Glasses Sport",
    description:
      "Durable and lightweight glasses for active lifestyles, perfect for outdoor activities.",
    image: "/products/6.png",
    price: 74.99,
    size: "Large",
    color: "Navy Blue",
    material: "Polycarbonate",
    frameShape: "Wraparound",
    lensType: "Anti-Reflective",
    weight: "20g",
    availability: "In Stock",
  },
  {
    id: 7,
    name: "Super Glasses Elegance",
    description:
      "Elegant and refined glasses that offer a sophisticated look for any formal occasion.",
    image: "/products/7.png",
    price: 79.99,
    size: "Medium",
    color: "Rose Gold",
    material: "Titanium",
    frameShape: "Oval",
    lensType: "Photochromic",
    weight: "23g",
    availability: "In Stock",
  },
  {
    id: 8,
    name: "Super Glasses Bold",
    description:
      "Bold frames for those who want to make a statement. Eye-catching and trendy.",
    image: "/products/8.webp",
    price: 89.99,
    size: "Medium",
    color: "Red",
    material: "Acetate",
    frameShape: "Square",
    lensType: "Mirrored",
    weight: "28g",
    availability: "In Stock",
  },
];
